{% set name = "sphinx_changelog" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97b4966f644df4e8176e9fbb650c2f9c852ca314a1cbe1c82711b56b8db03d08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools-scm
    - pip
  run:
    - python >=3.6
    - sphinx
    - towncrier >=22.8.0

test:
  imports:
    - sphinx_changelog
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://openastronomy.org
  summary: A changelog renderer for sphinx.
  description: |
    This package provides a sphinx extension designed to facilitate rendering
    changelogs into your sphinx documentation.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - licenses/LICENSE.rst
  doc_url: https://sphinx-changelog.readthedocs.io/en/latest/
  dev_url: https://github.com/OpenAstronomy/sphinx-changelog

extra:
  recipe-maintainers:
    - BSGalvan
    - Cadair
